spring:
  application:
    name: adb-bot

# 通用配置
adbConfig:
  defaultAfterActionWaitMillisecond: 1000
  adbBotActionSchedule: adbBotActionSchedule

# 腾讯自然语言处理接口
tencent_nlp_account:
  app_id: xxxx
  app_key: xxxxxx